export const EVENT_TYPES = [
  { id: 'et1', name: 'Wedding', icon: 'ring', color: '#6C63FF' },
  { id: 'et2', name: 'Birthday', icon: 'cake-variant', color: '#10B981' },
  { id: 'et3', name: 'Engagement', icon: 'diamond-stone', color: '#EC4899' },
  { id: 'et4', name: 'Corporate', icon: 'briefcase', color: '#0284C7' },
  { id: 'et5', name: 'Religious', icon: 'hands-pray', color: '#F59E0B' },
];

export const CATEGORIES = [
  { id: 'cat1', name: 'DJ', icon: 'music-box-outline', color: '#8B5CF6' },
  { id: 'cat2', name: 'Photography', icon: 'camera-outline', color: '#3B82F6' },
  { id: 'cat3', name: 'Tent', icon: 'tent', color: '#10B981' },
  { id: 'cat4', name: 'Halwai', icon: 'silverware-fork-knife', color: '#F59E0B' },
  { id: 'cat5', name: 'Decoration', icon: 'flower-tulip-outline', color: '#EC4899' },
  { id: 'cat6', name: 'Venue', icon: 'home-map-marker', color: '#EF4444' },
  { id: 'cat7', name: 'Car Rental', icon: 'car-sports', color: '#06B6D4' },
  { id: 'cat8', name: 'Bus Rental', icon: 'bus', color: '#6B7280' },
];

export const FEATURED_VENDORS = [
  {
    id: 'v1',
    name: 'The Grand Palace Resort',
    category: 'Venue',
    rating: 4.9,
    reviewsCount: 184,
    price: '₹1,80,000/day',
    location: 'Chhatarpur, New Delhi',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=600&auto=format&fit=crop',
    description: 'A premium venue featuring grand banquet halls and royal lawns accommodating up to 2000 guests.',
  },
  {
    id: 'v2',
    name: 'DJ Naman & Sound Systems',
    category: 'DJ',
    rating: 4.8,
    reviewsCount: 92,
    price: '₹45,000/event',
    location: 'Bandra, Mumbai',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
    description: 'Elite Bollywood DJ with custom light installations, line array speakers, and dynamic party mixes.',
  },
  {
    id: 'v3',
    name: 'Shiva Decorators & Florists',
    category: 'Decoration',
    rating: 4.7,
    reviewsCount: 110,
    price: '₹60,000/event',
    location: 'Indiranagar, Bangalore',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=600&auto=format&fit=crop',
    description: 'Premium fresh flower setups, theme styling, mandap layouts, and luxury stage backdrops.',
  },
  {
    id: 'v4',
    name: 'Royal Cuisine Halwai & Caterers',
    category: 'Halwai',
    rating: 4.9,
    reviewsCount: 156,
    price: '₹1,500/plate',
    location: 'Sector 62, Noida',
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=600&auto=format&fit=crop',
    description: 'Traditional sweets, gourmet multi-cuisine buffet counters, and elite hospitality teams.',
  },
];
