export const EVENT_TYPES = [
  { id: 'et1', name: 'Wedding', icon: 'ring', color: '#6C63FF' },
  { id: 'et2', name: 'Birthday', icon: 'cake-variant', color: '#10B981' },
  { id: 'et3', name: 'Engagement', icon: 'diamond-stone', color: '#EC4899' },
  { id: 'et4', name: 'Corporate', icon: 'briefcase', color: '#0284C7' },
  { id: 'et5', name: 'Religious', icon: 'hands-pray', color: '#F59E0B' },
];

export const CATEGORIES = [
  { id: 'cat1', name: 'DJ', icon: 'music-box-outline', color: '#8B5CF6' },
  { id: 'cat2', name: 'Photography', icon: 'camera-outline', color: '#3B82F6' },
  { id: 'cat3', name: 'Tent', icon: 'tent', color: '#10B981' },
  { id: 'cat4', name: 'Halwai', icon: 'silverware-fork-knife', color: '#F59E0B' },
  { id: 'cat5', name: 'Decoration', icon: 'flower-tulip-outline', color: '#EC4899' },
  { id: 'cat6', name: 'Venue', icon: 'home-map-marker', color: '#EF4444' },
  { id: 'cat7', name: 'Car Rental', icon: 'car-sports', color: '#06B6D4' },
  { id: 'cat8', name: 'Bus Rental', icon: 'bus', color: '#6B7280' },
];

const MOCK_SERVICES = [
  'Professional sound systems',
  'Ambient lights & lasers',
  'Experienced event coordinator',
  'Full set-up & dismantling',
  'Backup generator power',
];

const MOCK_REVIEWS = [
  {
    id: 'r1',
    userName: 'Karan Sharma',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100&auto=format&fit=crop',
    rating: 5,
    comment: 'Absolutely amazing! Highly professional and made our wedding party memorable.',
    date: '2 days ago',
  },
  {
    id: 'r2',
    userName: 'Priya Patel',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100&auto=format&fit=crop',
    rating: 4.8,
    comment: 'Great service, punctual, and highly cooperative. Definitely booking again.',
    date: '1 week ago',
  },
];

const MOCK_GALLERY = [
  'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=600&auto=format&fit=crop',
];

export const FEATURED_VENDORS = [
  {
    id: 'v1',
    name: 'The Grand Palace Resort',
    category: 'Venue',
    rating: 4.9,
    reviewsCount: 184,
    price: '₹1,80,000/day',
    priceValue: 180000,
    location: 'Chhatarpur, New Delhi',
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=600&auto=format&fit=crop',
    description: 'A premium venue featuring grand banquet halls and royal lawns accommodating up to 2000 guests. Complete with changing rooms, air conditioning, and top-tier security.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Central AC banquet hall', 'Spacious royal lawns', '20 luxury guest rooms', 'Valet parking (200+ cars)', '24/7 Power backup'],
    blockedDates: ['2026-06-25', '2026-06-28', '2026-07-02'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v2',
    name: 'DJ Naman & Sound Systems',
    category: 'DJ',
    rating: 4.8,
    reviewsCount: 92,
    price: '₹45,000/event',
    priceValue: 45000,
    location: 'Bandra, Mumbai',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
    description: 'Elite Bollywood DJ with custom light installations, line array speakers, and dynamic party mixes. Guaranteed to keep your guests on the dance floor all night long.',
    availability: 'Available Today',
    gallery: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
    ],
    servicesIncluded: ['High-bass JBL line arrays', 'Moving head laser lights', 'Smoke machine & sparkles', 'Customized event playlist', 'Backup mixer & mic'],
    blockedDates: ['2026-06-24', '2026-06-30'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v3',
    name: 'Shiva Decorators & Florists',
    category: 'Decoration',
    rating: 4.7,
    reviewsCount: 110,
    price: '₹60,000/event',
    priceValue: 60000,
    location: 'Indiranagar, Bangalore',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=600&auto=format&fit=crop',
    description: 'Premium fresh flower setups, theme styling, mandap layouts, and luxury stage backdrops. We bring your dream wedding aesthetic to life.',
    availability: 'Available Next Week',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Mandap setup with fresh roses', 'LED fairy light canopy', 'Bridal entry pathway decor', 'VVIP stage couch seating', 'Floral selfie booths'],
    blockedDates: ['2026-06-26', '2026-06-27'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v4',
    name: 'Royal Cuisine Halwai & Caterers',
    category: 'Halwai',
    rating: 4.9,
    reviewsCount: 156,
    price: '₹1,500/plate',
    priceValue: 1500,
    location: 'Sector 62, Noida',
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=600&auto=format&fit=crop',
    description: 'Traditional sweets, gourmet multi-cuisine buffet counters, and elite hospitality teams. Renowned for pure desi ghee preparations.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Live chaat & starter stations', 'Premium dry fruit sweets', 'Multi-cuisine dinner buffet', 'Trained waiter staff', 'Eco-friendly setup & cleanup'],
    blockedDates: ['2026-06-25'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v5',
    name: 'Pixel Story Weddings',
    category: 'Photography',
    rating: 4.9,
    reviewsCount: 204,
    price: '₹95,000/day',
    priceValue: 95000,
    location: 'Jubilee Hills, Hyderabad',
    image: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600&auto=format&fit=crop',
    description: 'Premium wedding films, modern portraits, and candid coverage. Capture every emotional detail in ultra high-definition video.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['2 Senior candid photographers', 'Cinematic wedding teaser video', 'Hardcover premium photobook', 'Drone cinematic coverage', 'High-res edited digital files'],
    blockedDates: ['2026-06-25', '2026-06-29'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v6',
    name: 'Elite Tent & Seating House',
    category: 'Tent',
    rating: 4.6,
    reviewsCount: 78,
    price: '₹35,000/event',
    priceValue: 35000,
    location: 'Salt Lake, Kolkata',
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=600&auto=format&fit=crop',
    description: 'Weatherproof premium tents, visual lighting setups, and luxury sofas for high capacity wedding and corporate functions.',
    availability: 'Available Next Week',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Waterproof German hangar tent', 'Premium carpet flooring', 'Sofas & round banquet tables', 'Ceiling chandelier layouts', 'High speed cooling fans'],
    blockedDates: ['2026-06-28'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v7',
    name: 'Luxury Wedding Cars',
    category: 'Car Rental',
    rating: 4.8,
    reviewsCount: 65,
    price: '₹25,000/day',
    priceValue: 25000,
    location: 'Gurugram, Haryana',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&auto=format&fit=crop',
    description: 'Premium vintage models and sports convertibles for couple entries. Chauffeur driven with wedding flower decorations included.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Chauffeur in uniform', 'Premium fresh flower decor', 'Fuel & toll taxes included', '24/7 roadside assistance', 'Complimentary refreshments'],
    blockedDates: [],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v8',
    name: 'Event Transit Bus Services',
    category: 'Bus Rental',
    rating: 4.5,
    reviewsCount: 42,
    price: '₹18,000/day',
    priceValue: 18000,
    location: 'Hadapsar, Pune',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=600&auto=format&fit=crop',
    description: 'AC Volvo coaches and mini buses for seamless guest transportation from hotels to venues.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['45-seater luxury AC Volvo', 'Pushback seats with seatbelts', 'GPS tracker & CCTV', 'Professional verified driver', 'Spacious luggage compartment'],
    blockedDates: ['2026-06-25'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v9',
    name: 'Starlight Beats DJ & Laser',
    category: 'DJ',
    rating: 4.7,
    reviewsCount: 54,
    price: '₹30,000/event',
    priceValue: 30000,
    location: 'Adyar, Chennai',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
    description: 'LED walls, line array subwoofers, and dynamic EDM tracks matching global festival standards.',
    availability: 'Fully Booked',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Pioneer DJ console setup', 'Co2 jet blowers', 'Truss lighting structures', 'Wireless microphones', 'Customized digital invitation sound'],
    blockedDates: ['2026-06-23', '2026-06-24', '2026-06-25', '2026-06-26'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v10',
    name: 'Moments Captured Photography',
    category: 'Photography',
    rating: 4.8,
    reviewsCount: 89,
    price: '₹70,000/day',
    priceValue: 70000,
    location: 'Hazratganj, Lucknow',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=600&auto=format&fit=crop',
    description: 'Candid wedding frames, cinematic reels, and drone coverage of ceremonies.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Candid + Traditional coverage', '15-page signature photo album', 'Pre-wedding shoot discount', 'Drone footage', 'Raw footage deliverables'],
    blockedDates: ['2026-06-28'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v11',
    name: 'Maharaja Tents & Water Proofing',
    category: 'Tent',
    rating: 4.4,
    reviewsCount: 38,
    price: '₹55,000/event',
    priceValue: 55000,
    location: 'Malviya Nagar, Jaipur',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600&auto=format&fit=crop',
    description: 'Palace themes, royal waterproof structural tents, and velvet carpets for outdoor celebrations.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Royal theme canopy setups', 'Velvet floor carpets', 'Misting fans for summer', 'Fire extinguishers on site', 'Decorative boundary drapery'],
    blockedDates: [],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v12',
    name: 'Bikaner Sweets & Catering',
    category: 'Halwai',
    rating: 4.8,
    reviewsCount: 198,
    price: '₹950/plate',
    priceValue: 950,
    location: 'Chandni Chowk, Delhi',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?q=80&w=600&auto=format&fit=crop',
    description: 'Traditional desi ghee sweets and North Indian wedding treats prepared by generational chefs.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Live jalebi & rabri counter', 'Generational Rajasthani chefs', 'Clean copper cooking utensils', '100% vegetarian preparations', 'Mocktail welcome bar'],
    blockedDates: ['2026-06-26'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v13',
    name: 'Vibrant Colors Decor',
    category: 'Decoration',
    rating: 4.9,
    reviewsCount: 147,
    price: '₹75,000/event',
    priceValue: 75000,
    location: 'Salt Lake, Kolkata',
    image: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?q=80&w=600&auto=format&fit=crop',
    description: 'Modern glassmorphism elements, fairy lights, and ceiling drapes matching premium visual benchmarks.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Fairy light tree wraps', 'Glass centerpieces on tables', 'Vibrant entry backdrop arch', 'Artificial flower ceilings', 'Custom name neon signs'],
    blockedDates: ['2026-06-27', '2026-06-30'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v14',
    name: 'Emerald Banquets & Lawns',
    category: 'Venue',
    rating: 4.8,
    reviewsCount: 220,
    price: '₹2,20,000/day',
    priceValue: 220000,
    location: 'Ghatkopar, Mumbai',
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=600&auto=format&fit=crop',
    description: 'Central air-conditioned halls and landscaped gardens with multi-cuisine catering support.',
    availability: 'Fully Booked',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['2 Large luxury AC halls', 'Outdoor lawn (1000 guests)', 'Separate dressing rooms', 'In-house decorators allowed', 'Underground parking (100 cars)'],
    blockedDates: ['2026-06-23', '2026-06-24', '2026-06-25', '2026-06-26', '2026-06-27'],
    reviews: MOCK_REVIEWS,
  },
  {
    id: 'v15',
    name: 'Presidential Car Fleet',
    category: 'Car Rental',
    rating: 4.9,
    reviewsCount: 77,
    price: '₹40,000/day',
    priceValue: 40000,
    location: 'Whitefield, Bangalore',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=600&auto=format&fit=crop',
    description: 'Luxury sedans (BMW, Mercedes) and premium SUV listings. Clean interior sanitization and professional chauffeurs.',
    availability: 'Available Today',
    gallery: MOCK_GALLERY,
    servicesIncluded: ['Luxury Mercedes S-class', 'Polite English speaking driver', 'Cold drinks & wipes onboard', 'Premium leather seating', 'Flexible hourly packages'],
    blockedDates: ['2026-06-25'],
    reviews: MOCK_REVIEWS,
  },
];
export default FEATURED_VENDORS;
